# Generated by Django 5.2 on 2025-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature_teammember_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
