# Generated by Django 5.2 on 2025-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feature_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='discount_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
