# Generated by Django 5.2 on 2025-05-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instagramimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
