# Generated by Django 5.2 on 2025-05-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_menu_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='title',
        ),
    ]
