# Generated by Django 5.2 on 2025-05-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogpost_author_blogpost_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
    ]
